### ISSUE TITLE
Components has both CSS and SCSS

### ISSUE THREAD

**Issue by serhanelmali** [DesignSystemsOSS/community#21]
Components have got both CSS and SCSSfiles and SCSS files also written as standard CSS. So it's unnecessary to have unused SCSS files like "main.scss", "Home.scss", "Projects.scss".

**Comment by yashsehgal** [comment]
Yeah, That's something logical. We would surely move to this thing but right now there are some things like `-webkits` and all are also being used in the CSS files and that's why we write our code into SCSS Modules.

But Yeah, We can switch to plain CSS in the future - Thanks for the good advice. Appreciate it :)

**Comment by yashsehgal** [comment]
Also, We would love to have you on our Discord Server.
[Join The DesignSystems Discord](https://discord.gg/gR9fj9fj)
